# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
# dsn: "postgres://postgres:postgres@127.0.0.1:5432/go_restful?sslmode=disable"

##  NOTE : all config keys should be  lowercase
# 配置键必须全小写！！！ 参考 https://github.com/jinzhu/configor

dbuser: "root"
dbpass: ""
dbhost: "127.0.0.1"
dbport: 3306

dbdriver: "mysql"
# 此处需要动态构造数据库连接！！！ conn_url 形式还稍微统一点 可以考虑使用  URL形式 有许多连接参数需要查文档哦
# connStr := "postgres://pqgotest:password@localhost/pqgotest?sslmode=verify-full"
# db, err := sql.Open("postgres", connStr)
# 	dns := fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8", dbuser, dbpwd, dbhost, dbname)
#   NOTE: <dbuser> <dbpass> <dbhost> <dbport> <dbname> 这几个占位符是指定的不能自己瞎搞哦
datasourcefmt: "<dbuser>:<dbpass>@tcp(<dbhost>:<dbport>)/<dbname>?charset=utf8"

appname: "gii-console"

contacts:
  - name: yiqing
    email: yiqing@qq.com
