# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
# dsn: "postgres://postgres:postgres@127.0.0.1:5432/go_restful?sslmode=disable"

##  NOTE : all config keys should be  lowercase
# 配置键必须全小写！！！ 参考 https://github.com/jinzhu/configor

dbuser: "root"
dbpass: ""
dbhost: "127.0.0.1"
dbport: 3306

appname: "gii-console"

contacts:
  - name: i test
    email: test@test.com
